namespace Domain.Enums
{
    public enum AnimeGenre
    {
        Action,
        Adventure,
        Comedy,
        Drama,
        Fantasy,
        Horror,
        Mystery,
        Romance,
        ScienceFiction,
        SliceOfLife,
        Sports,
        Supernatural,
        Thriller,
        Historical,
        Mecha,
        Music,
        Psychological,
        School,
        Isekai,
        Military,
        MartialArts,
        Shounen,
        Shoujo,
        Seinen,
        Josei,
        Harem,
        ReverseHarem,
        Ecchi,
        Yaoi,
        Yuri
    }
}